### ISSUE TITLE
Add copy/paste for notes

### ISSUE THREAD

**Issue by speddle** [esaracco/wopits#2]
I would like to be able to do a group select of Notes with the mouse.
Then ctrl-clk **unselected** Notes to **add to the slection**, or ctrl-clk **selected** Notes to **remove from the selection**.
Then maybe ctrl-c/v/x support to move on the existing wall or to a new wall.
Or maybe drag the selection with the mouse.

**Comment by esaracco** [comment]
Done (0.44alpha1).
Use ctrl+click to select notes. A menu will appear, displaying some user help.
Keep me in touch!

**Comment by esaracco** [comment]
@speddle Can we close this issue?

**Comment by speddle** [comment]
This looks quite useful. I have been looking it over and have a few comments suggestions.

1. It looks like I get the copy/paste popup on the CTRL-selection of the first note. If I change my mind or get confused I would like to **clear the selections** and menu by pressing **ESC**.
2. Once I have made my selection can you provide keyboard aliases for the selection menu options? 
Copy CTRL-C, Cut CTRL-X, Delete=DEL, Colour ??? not sure.
3. CTRL-click for paste is fine. Can you also support the MS standard CTRL-V based on cursor location? Also is there an option to turn off the popup before the paste? You could just go ahead and paste it and back it out if the next key is ESC.

Designing a user interface that is intuitive to the user can be difficult. After all intuitive is in the eyes of the user, and we all have different backgrounds. So far I think you have done a great job. If you think these suggestions would be of value to other users great.  

Thanks!
BTW: php is weird!

**Comment by esaracco** [comment]
@speddle Done (v0.46alpha1). Thanks for these great ideas!

**Comment by speddle** [comment]
Hey that is nice!
I wonder if other people like these additions too?

Thanks
