### ISSUE TITLE
Installing on a hosting service

### ISSUE THREAD

**Issue by lukenavo** [esaracco/wopits#4]
Hi, I'm searching for a sticky notes software that is able to do brainstorming with my student.
I think your could be fine but I need to install on a simple web hosting service. I can't add software of any kind.
Is it possible to install wopits only with php and mysql? 
Thanks,
Luca Navone

**Comment by esaracco** [comment]
@lukenavo To install wopits, you will need PHP, Apache, MariaDB or PostgreSQL, and Swoole. Take a look at the [README](https://github.com/esaracco/wopits/blob/master/app/doc/README.md).

**Comment by lukenavo** [comment]
Yes, I read It and I think the problem Is swoole. I cannot install It on
server.
Thank you anyway!
Luca

Il gio 12 nov 2020, 16:08 Emmanuel Saracco <notifications@github.com> ha
scritto:

**Comment by esaracco** [comment]
@lukenavo You can always try [scrumblr](https://github.com/aliasaria/scrumblr). Less features than wopits, but easier to install :-)

**Comment by lukenavo** [comment]
Thanks for the tip! I'll try it.

Il 12 novembre 2020 16:30:13 CET, Emmanuel Saracco <notifications@github.com> ha scritto:
>@lukenavo You can always try
>[scrumblr](https://github.com/aliasaria/scrumblr). Less features than
>wopits, but easier to install :-)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/esaracco/wopits/issues/4#issuecomment-726150421

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.
